# Generated by Django 5.0.2 on 2024-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=60, null=True)),
                ('notas', models.TextField(null=True)),
            ],
        ),
    ]
