# Generated by Django 5.0.2 on 2024-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_remove_contactos_direccion_remove_contactos_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='contactos',
            name='titulo_nota',
        ),
        migrations.AddField(
            model_name='contactos',
            name='direccion',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='notas',
            field=models.TextField(null=True),
        ),
    ]
